### ISSUE TITLE
Landing/Enter Cobuy "chat"

### ISSUE THREAD

**Issue by danalexilewis** [root-systems/cobuy#1]
When I go to app.cobuy.nz, I want to enter my username/login, so that i can enter the app with an identity.

**Comment by ahdinosaur** [comment]
@agentlewis i thought we weren't doing login, accounts, groups, etc in Alpha?

**Comment by danalexilewis** [comment]
yep i dont mean that you have an account. only a user name for that occurence of entering the app. realising now it means you couldnt go away and come back. the idea was that two agents could be active at the same time and see each other on there

**Comment by danalexilewis** [comment]
@ahdinosaur ^

**Comment by danalexilewis** [comment]
we could also just say what ever username they want to use they can? and if its already been used we just ad a number on the end?

**Comment by michael-smith-nz** [comment]
fixed with #59
