### ISSUE TITLE
trigger creation and linkage of group agent on order && task plan creation

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#113]
@ahdinosaur would this work/help:

// startOrderEpic filters actions of type start-order
// mergeMap/map to create-task-plan action for the top-level task plan

// createTaskPlan epic filters actions of type create-task-plan
// check if this is the creation of a parent task plan, and
// mergeMap with create-task-plan action(s) for child task plans
// check if parent task plan has a related group agent, and if not
// mergeMap with create-agent of group type action, payload includes task plan id to be linked

// createAgent epic filters actions of type create-agent
// check if this is creation of a group agent, and if so
// mergeMap with update-task-plan action, whose payload includes
// task-plan id that came with the create-agent payload
// and new group agent id to add to the corresponding task plans

**Comment by ahdinosaur** [comment]
an alternative approach is we handle this in the server-side feathers services as after hooks. the pro is it avoids complex epics to ensure objects are created in order, plus it can eventually be done as a database transaction. this depends on our pages having queries to ask for all relevant data and not depending on server-side response, but we do this anyways.
