### ISSUE TITLE
change offering form to match data model

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#114]
Child task of #36

@ahdinosaur and i note certain structural differences between the data coming out of the offerings form, and the data model for resource types.

example of current offering form output ("one crate of 16 cartons of 12 eggs"):

```
offering: {
  name: "a crate of egg cartons",
  quantity: 1,
  unit: 'ea',
  resource: 'crate',
  offering: {
    quantity: 16,
    unit: 'ea',
    resource: 'carton',
    offering: {
      quantity: 12,
      unit: 'ea',
      resource: 'egg'
    }
  }
}
```

sample example given our data model:

```
resourceType: {
  name: "a crate of egg cartons",
  items: [ { value: 1, unit: "ea", resource: "crate" },
          { value: 16, unit: "ea", resource: "carton of eggs" } ]
}

resourceType: {
  name: "a carton of eggs",
  items: [ { value: 1, unit: "ea", resource: "carton" },
            { value: 12, unit : "ea", resource: "egg" } ]
}
```

notes on the comparison:

- the current output from the form privileges 'semantics', i.e. being more 'human-comprehensible'
- the data model privileges and presupposes a normalized, atomistic approach, where items/resources (especially the 'containers') can be reused

challenges for the form:

- can we get the best of both worlds? could we potentially do some normalization under the hood, while the UI is preserved?
- is there a limit to how much we could do under the hood? what if multiple different containers had the same name? how would we automate their reusability?

**Comment by ahdinosaur** [comment]
@agentlewis thoughts: can we do price specifications based on abstract values? as in, "you get this price if you are part of Enspiral". or, "you get this price based on what level of membership of the coop you are".
