### ISSUE TITLE
add type json-schemas for all data models

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#118]
database models: https://github.com/root-systems/cobuy/wiki/Models

**Comment by ahdinosaur** [comment]
should we make this a priority for this sprint? @gregorykan @agentlewis

i wonder if it would help better describe the app for on-boarding new devs.

**Comment by gregorykan** [comment]
@ahdinosaur @agentlewis given we are (abruptly?) in a transition period, with @sarah-arrrgh and @NotThatSmith coming on board, and me heading off, i think it makes sense to prioritize this issue to facilitate onboarding, i.e. for us to straddle the 'present' (what we had planned for this sprint) and also the future (facilitating onboarding)

**Comment by ahdinosaur** [comment]
i also recommend we use something like [`json-schema-faker`](https://www.npmjs.com/package/json-schema-faker) in our tests and storybooks so our fake test data is always in sync with our schemas.

**Comment by danalexilewis** [comment]
I agree - I assume it makes debugging easier?

**Comment by danalexilewis** [comment]
ajv for validation - https://github.com/epoberezkin/ajv

**Comment by ahdinosaur** [comment]
understanding JSON schema: https://spacetelescope.github.io/understanding-json-schema/

**Comment by ahdinosaur** [comment]
examples:

## agent profile

```js
{
  id: 'agents/Profile',
  title: 'Profile',
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      description: 'id referencing profile...'
    },
    agentId: {
      type: 'integer',
      description: 'id referencing agent...'
    },
    name: {
      type: 'string',
      description: 'agent name...'
    },
    description: {
      type: 'string',
      description: 'agent biography...'
    },
    avatar: {
      type: 'string',
      format: 'url',
      description: 'agent avatar image link...'
    }
  }
}
```

## agent with profile


```js
{
  id: 'agents/Agent',
  title: 'Agent',
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      description: 'id referencing agent...'
    },
    profile: {
      $ref: 'agents/Profile'
    }
  }
}
```

**Comment by ahdinosaur** [comment]
in general, i think we'll have schemas to represent:

- database models (as in the wiki page)
- redux state models (same as database?)
- getter models (composed from database / redux state models, referencing related models)
- component models? (specific to each component, best to re-use as much as possible, probably out-of-scope for here)

**Comment by michael-smith-nz** [comment]
How do we want to use these schemas? Do we want this for Stories and tests only? Or do we want to validate when running in a debug environment as well? I think Ideally we'd want all three, although I haven't looked into tooling

**Comment by ahdinosaur** [comment]
> How do we want to use these schemas?

on my mind:

- generating fake data for tests and stories
- validating server endpoints with [feathers `validateSchema` hook](https://docs.feathersjs.com/api/hooks-common.html#validateschema)
- maybe (in development) as React component prop types (there's probably a module for this)
- maybe (in development) as a redux middleware to validate the state tree on every state change

i'm happy to use it everywhere that feels helpful, then we can sort out how to strip out in production later.
