### ISSUE TITLE
make clear what non-dev tasks are be to done

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#119]
we're a product company now. if we don't put these tasks in our sprints, then it falls on someone else. not much of a problem now, but will be sometime soon. rather than outsource to someone outside, we'd rather turn our dev sprints into product sprints.

also allows devs to work on things when they are blocked on dev.

TODO:

- [ ]  add these tasks to tour waffle / GitHub board

initial thoughts:

- communications
  - emails
  - facebook
- marketing
  - publish open source
  - publish blog posts
- sales

**Comment by ahdinosaur** [comment]
made roles:

-  role: groom our kanban board #129 
-  role: respond to email communications #134 
-  role: respond to Facebook communications #133 
-  role: respond to Twitter communications #135 
-  role: write content on blog, cross-post to Facebook + Twitter #107 

one-off tasks

- setup Cobuy blog on Medium #136 

@agentlewis what else do you think is missing?
