### ISSUE TITLE
clicking "done" creates a task work to mark task completion

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#126]
moving out from #120 

job story: when i am done with a task and want to mark it as complete, i click "done" and a TaskWork is created to reference the associated TaskRecipe (and optional TaskPlan).

![screenshot_20170816_144226](https://user-images.githubusercontent.com/719605/29345185-22ce739e-8291-11e7-9e7e-6b32157e7d41.png)

this task should then show as "completed" on any page referencing it.

**Comment by michael-smith-nz** [comment]
I think I'll work on this next since I ran into this with #138
