### ISSUE TITLE
Empty Taskplan params

### ISSUE THREAD

**Issue by michael-smith-nz** [root-systems/cobuy#132]
Logging issue because I'm going down a rabbit hole.

Is it possible to have an empty `params` property on `taskPlan`?
This getter is currently breaking order creation.
Happy to fix, but needed to know the above question first.

https://github.com/root-systems/cobuy/blob/4f81f6a34b09d65f85611188677e6c14ea2e9713/tasks/getters/getEnhancedTaskPlans.js#L18

**Comment by ahdinosaur** [comment]
> Is it possible to have an empty params property on taskPlan?

yes! probably best if we coerce `undefined` and `null` into `{}`, but it's definitely possible to have an empty object for `params`.

>  This getter is currently breaking order creation

yeah, the "order pre-req" tasks expect `params.contextAgentId`, so we know how to update the group profile and invite group members. but others tasks, say like the "setup your personal profile" task don't need this context agent.

**Comment by michael-smith-nz** [comment]
Turns out the problem with the broken order creation getter was that `params` was not writing to the database because we were not encoding the object as a string before writing. Should be fixed in https://github.com/root-systems/cobuy/commit/abd1248ed7d8354e14f97c3758092ecd0560c0c8
