### ISSUE TITLE
token / capability service

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#159]
we will need a few [token](https://en.wikipedia.org/wiki/Security_token) / [capability](https://en.wikipedia.org/wiki/Capability-based_security) features in Cobuy:

- [group invites](https://github.com/root-systems/cobuy/issues/93)
- [reset password](https://github.com/root-systems/cobuy/issues/58)
- secure download link

these are the services i've made so far with Mischa in Minded, but for Cobuy i wonder if it is advantageous to combine these into a single service.

possible data model:

```yml
- id (increments)
- agentId (integer)
- type (string)
- params (json)
- isConsumed (boolean)
- isRemoved (boolean)
```

where `type` is a sting referencing type of token: `inviteMember`, `resetPassword`, `downloadBlob`
where `params` would be flexible for each type of token:

group invites: `groupId`, `roles`
download: `blobId`

thoughts?

**Comment by ahdinosaur** [comment]
forgot to mention that json web tokens are bigly supported by [`feathers-authentication`](https://docs.feathersjs.com/api/authentication/server.html) and related modules. so the tokens are easy, the question is whether we want to provide a data wrapper around the tokens so we can provide a better user experience.

i notice Feathers has a new [authentication management system](https://docs.feathersjs.com/api/authentication/local-management.html) that is similar to this, worth us looking into.

**Comment by ahdinosaur** [comment]
https://blog.feathersjs.com/how-to-setup-email-verification-in-feathersjs-72ce9882e744

**Comment by ahdinosaur** [comment]
looking into this meow. the [`feathers-authentication-management`](https://github.com/feathersjs/feathers-authentication-management) module is nice, but it doesn't match _exactly_ with the register -> invite members -> start order flow i had in mind.

what it does provide:

- a way to check unique email, cell phone number, etc on each credential
- each credential has a boolean `isVerified` (whether the email is verified or not)
- each credential has short and long verification codes
- a user is "verified" by being sent an email or text message with the code, which they can send back to the app
- each credential has short and long password reset codes
- a user can reset their password #58 by being sent an email or text message with the code, which they can send back to the app with a new password

they expect a typical user register -> verify flow:

- i sign up for the app, creating a credential
- i get an email "hey thanks for signing up", here's a link to verify your email
- if i want to reset my password, i am emailed a link to make it happen

i had in mind a different flow:

- the group admin signs up for the app, creating a credential
- the group admin gets an email "hey thanks for signing up", here's a link to verify your email
- the group admin invites new group members
  - if the group member already has a credential (same email), they are added to the group
  - otherwise, the new group member has a credential created and is sent an email "hey you've been invited to group", here's a link to setup your account (implicitly verify your email _AND_ reset your password at once)

hmmmm

**Comment by mischa-s** [comment]
Instead of type we could have service and method (for example: agents, patch). This way we wont have to hardcode special token types and instead the logic is implemented as before hooks on the token service that is added within the corresponding authorised service.

In general, we want to have as much authorisation logic (what are you able to do) in the token creation before hooks, so the token is a capability that describes your access to a service method, rather than authorising in the token consumption.

For the case of download blob where it must be an http route, we could have the route handler pass the token to the service to maintain a single type of token access.

**Comment by mischa-s** [comment]
- should `service` and `method` be part of params?
- should we add a `expiresAt` field? then the json tokens never expire and we check expiration in the database
- should we have a related table of `tokenConsumes`, which have fields `id`, `tokenId`, and `consumedAt`
  - this way different services can use the related consumes as they wish, some might only want a token to be consumed once (invite new user), others might just want to track / limit consumes (download files)

**Comment by mischa-s** [comment]
Instead of `expiresAt` there should be a `createdAt` field and then if types of tokens need to be time limited the service can compare the allowed time to the time elapsed since the token was created

**Comment by ahdinosaur** [comment]
data model (with help from @mischa-s, since we are exploring this pattern in parallel on a separate contract project)

## tokens

- id (increments)
- agentId (integer references agents.id)
- service (string)
- method (enum: find, get, create, update, patch, remove)
- params (json)
- jwt (text)
- createdAt (timestamp defaultTo(knex.fn.now())

## tokenConsumes

- id (increments)
- tokenId (integer references tokens.id)
- createdAt (timestamp defaultTo(knex.fn.now())
