### ISSUE TITLE
create consumer / supplier relationships

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#162]
since consumers and suppliers are both agents of type group, we need a way to find all the suppliers for a given consumer (group).

**Comment by ahdinosaur** [comment]
had a chat with @Julietbc about this. probably makes sense to only create a single `supplier` relationship from the consumer (buying group) agent to the supplier agent.

to be specific:

```js
const relationship = {
  sourceId: consumerAgentId,
  relationshipType: 'supplier',
  targetId: supplierAgentId
}
```

then a query for all suppliers for a given buying group is:

```js
relationshipsService.find({
  query: {
    sourceId: consumerAgentId,
    relationshipType: 'supplier'
  }
})
.then(relationships => {
  return Promise.all(relationships.map(relationship => {
    const { targetId: supplierId } = relationship
    return agentsService.get(supplierId)
  }))
})
```

**Comment by iainkirkpatrick** [comment]
feels to me like this is done? i.e. there are areas in the app now where we query for suppliers based on the `relationshipType: 'supplier'`

@Julietbc @ahdinosaur ?

**Comment by Julietbc** [comment]
Yeah idk why this is still here @iainkirkpatrick  I thought it had been closed
