### ISSUE TITLE
app hook for current agent

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#166]
at the moment `feathers-authentication` provides the current credential as `hook.params.credential`, but more often we want the associated agent, profile, and/or relationships.

this ticket is to create a [app hook](https://docs.feathersjs.com/api/hooks.html#application-hooks) that fetches the current agent and adds it to `hook.params.agent`.

potentially we also add hooks for profile and relationships, but maybe those should be hook functions that can be called in specific services that require them, so we don't fetch many associated objects on every single request.

**Comment by michael-smith-nz** [comment]
@ahdinosaur is this what you were thinking? https://github.com/root-systems/dogstack-agents/pull/7
Wasn't too sure if you wanted it in `dogstack-agents` or not.

If that's on the right track, I'll also add a relationships hook

**Comment by ahdinosaur** [comment]
@NotThatSmith yeah, awesome! left some comments in the pull request.
