### ISSUE TITLE
component: order summary

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#178]
this component displays information when an order is closed.

should include list of "commitments" given aggregate of intents.

TODO

- [ ] create sketch with component architecture / box model
- [ ] storybook each major component with various props

related to: #43, #40

**Comment by michael-smith-nz** [comment]
Questions to work out:

- Need a supplier summary(no individual order info), group summary and individuals summary as well as a whole groups?
- How does an order close?
- What does the data shape look like? List of products and amount with at least one ordered. Total price. Unit cost. Similar to invoice, total price, etc.
- How does a user see this summary? Most things at the moment are task based.
- How does a user see this historical summaries? Do we need this for MVP?
- What supplier information do we need? Address, phone number etc.


Assumptions
- No intent info, "asked for 20, only got 3", etc.
- Only admin can action the summary. Admin will make changes before summary created (don't have functionality yet)
- OK for everyone in group to see order summary with individuals order information

Tickets to create:
- Basic edit group plan admin edit
- How does an order close?

TODO:

- Look into data shape, see what's not already there.
- Create storybook with dummy shape and data
...

**Comment by michael-smith-nz** [comment]
Data needed for supplier summary:

- Supplier details
- Order date completed
- order items
  - unit price
  - quantity
- total price

**Comment by michael-smith-nz** [comment]
Will be using the `OrderPlan` model as a base for `OrderSummary` component https://github.com/root-systems/cobuy/wiki/Models#orderplan

**Comment by michael-smith-nz** [comment]
TODO:
- analyse what tickets need to be created/split off

**Comment by michael-smith-nz** [comment]
Notes from the call with Iain:

- Is it too early to work on plumbing?
  - Only intent components have been made, no plumbing
- How should the user see the order summary?
  - Could be task-based?

TODO:

- Work on data shape of order, orderIntent and product intent. This will cross over with Order Close work(#210)

**Comment by michael-smith-nz** [comment]
Data shape. @ahdinosaur Would love your feedback before we go too far down the rabbit hole. 

Should an `OrderPlan` reference an `OrderIntent` or be separate?


- order
  - orderIntents
    - agent
    - id
    - disiredQuantity
    - productId
      - priceSpecId
  - orderPlans
    - id
    - orderIntentId
    - quantity

**Comment by ahdinosaur** [comment]
> Should an OrderPlan reference an OrderIntent or be separate?

yes, but it's optional since you can plan without an intent.

the orderPlan needs to reference the productId and priceSpecId, since we can't depend on the intent for these values since it might not exist.

otherwise looks sweet on first pass!

**Comment by ahdinosaur** [comment]
> How should the user see the order summary? 

when they have a task to review the order summary. 😄 later we might want a way to check the history of an order, but i think we can skip this for now.

> Is it too early to work on plumbing? 

the component is very important to demo, the plumbing will be easier when the intent plumbing is done.

**Comment by michael-smith-nz** [comment]
Great. Thanks @ahdinosaur, my assumption was that you can only have an orderplan with an intent so that's good to know.

**Comment by michael-smith-nz** [comment]
Updated data shape

- order
  - orderIntents
    - agent
    - disiredQuantity
    - productId
      - priceSpecId
  - orderPlans
    - agent
    - quantity
    - productId
      - priceSpecId
