### ISSUE TITLE
deploy Tapin staging server

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#185]
cobuy-staging.tapin.nz

**Comment by danalexilewis** [comment]
Can I have an update on this? Just been asked how we are going for demoing this at the end of the month. And in two prep pitches between now and then.

**Comment by danalexilewis** [comment]
And as a general process what do people think of doing releases/deployments to staging every Monday.

**Comment by iainkirkpatrick** [comment]
@agentlewis I just picked this ticket back up again last night - we have a Root Systems Heroku team account now (which I will send you an invite to), I've pushed the latest `master` to a deployment but it's bailing at the moment - I suspect we will have to make some changes to the way we are doing config at the moment, or at least there's a problem to address there.

Yeah I'm keen on the idea of regular releases to staging. Heroku looks like they have a new thing called ['pipelines'](https://devcenter.heroku.com/articles/pipelines) where you have your staging and prod, but also 'review' deployments - i.e. any time someone makes a PR, Heroku creates a deployment for that branch. Could be useful (even if we won't deploy prod to heroku?) so that we can have deployed instances of features, but also staging that is stable for your demos.

**Comment by iainkirkpatrick** [comment]
When we get to having a prod server then we should think about which branches match which deployment - i.e. `master` to prod, `staging`? to staging... for now i reckon we just use `master` for staging and continue to PR the way we have been. at least until @ahdinosaur gets back :)

**Comment by danalexilewis** [comment]
Yeah pipelines are cool. Main thing is we don’t want staging-cobuy.tapin.nz to be broken. It should always be ready for demo.

 Other feature branch deployments could be cool - maybe we have other sub domains - dev-one.cobuy.nz, dev-two.cobuy.nz etc

Also note without continuous integration and tests we can’t do continuous deployment. It would be pretty cool to get Travis set up for doing some of these.

**Comment by ahdinosaur** [comment]
i'd do separate branches for staging and production, where the production branch is deployed to the demo app, which should probably just be `cobuy.tapin.nz` yeah?

**Comment by iainkirkpatrick** [comment]
current stumbling block:
- app deployed to staging, new github app for the staging deployment, but getting 500 internal server error when the callback returns from github... not sure why :/ needs a bit of diving into dogstack-agents credentials code methinks

noticing that the githubId is not persisted to the table on staging, but is locally.

**Comment by iainkirkpatrick** [comment]
@ahdinosaur will look at this with you or pass on to you i think, have spent some time investigating to no avail...

getting a `Error: connect ECONNREFUSED 127.0.0.1:1025` when attempting to register with email and password, first thought was something sockety breaking but can't see what

**Comment by ahdinosaur** [comment]
> app deployed to staging, new github app for the staging deployment

@iainkirkpatrick how did you add the GitHub app config to the staging deployment? i'd expect this to be added to https://github.com/enspiral-pods/cobuy-config in `staging` or `production.js`. i also think we'd need a way to automatically copy this config in during heroku deploy, have you done that somehow?

**Comment by ahdinosaur** [comment]
> getting a `Error: connect ECONNREFUSED 127.0.0.1:1025` when attempting to register with email and password, first thought was something sockety breaking but can't see what

@iainkirkpatrick port 1025 is [`maildev`](https://github.com/djfarrelly/maildev). similar configuration, it sounds like you are using the development config.

**Comment by iainkirkpatrick** [comment]
ohhhhhhh!!! of course. yeah the config at the moment is in large JSON string in the heroku config vars - yeah had the thought that copying in config from the config repo would be ideal, but seems like we'd need some .sh scripts or something to do that... thought it was easier for now to just dump into config vars. but yeah totally includes the maildev stuff @ahdinosaur

**Comment by ahdinosaur** [comment]
yeah, looking at the heroku config meow, keen to take this over @iainkirkpatrick. did you make accounts for any of the authentication services? you mention making a GitHub app, how will i be able to manage the settings, for example the callback url?

**Comment by iainkirkpatrick** [comment]
sweet @ahdinosaur - theres a new `cobuy-staging` app under the root systems account on Github, maybe this link works https://github.com/organizations/root-systems/settings/applications/599918

**Comment by ahdinosaur** [comment]
hey @agentlewis, who manages `tapin.nz` domain?

can they add a `CNAME` from `cobuy.tapin.nz` to `cobuy.tapin.nz.herokudns.com`?

**Comment by ahdinosaur** [comment]
my thinking on `cobuy.tapin.nz` is that we treat it like our _production_ deployment of Cobuy for Tapin.

then, as you mentioned Dan, we might want to have some development staging servers, so we can test or demo features in a production environment, but those are non-specific to Tapin. we can start with `cobuy.rootsystems.nz` to be this?

**Comment by ahdinosaur** [comment]
we need to choose a transactional email provider!

any preference between:

- [Mailgun](https://www.mailgun.com/) 
- [Sendgrid](https://sendgrid.com/)
- [Mandrill](http://mandrill.com/)

i'm leaning towards Mailgun.

**Comment by iainkirkpatrick** [comment]
mandrill is the only one i've used before - any reason you like Mailgun @ahdinosaur ? are they all much-of-a-muchness?

**Comment by ahdinosaur** [comment]
@iainkirkpatrick developer-friendly, have a free plan, just cuz really. agree they are all a bit the same, but it's about who we want to start a relationship with.

**Comment by ahdinosaur** [comment]
TODO:

- [x] fix styles on deployed site
- [x] test user flow
  - [x] register
    - [x] with email
    - [x] with GitHub
    - [x] with Facebook
      - [x] create Facebook app
    - [x] with Google
      - [x] create Google app
  - [x] sign up
  - [x] basic updates
  - [x] emails send
- [x] force ssl
- [x] fix production configs
- [x] fix production database
- [x] ~setup Git LFS with heroku~

**Comment by ahdinosaur** [comment]
darn, heroku doesn't support Git LFS. we should push the images up to some file hosting website, like [Cloud Files](https://www.rackspace.com/en-au/cloud/files) or Amazon S3 or [Catalyst Cloud's OpenStack Object storage](http://docs.catalystcloud.io/object-storage.html).

more TODO:

- [x] setup cloud file account
- [x] create guide for how to get started and sync local files (in Git LFS) with remote file containers, including making them accessible over a CDN
- [x] add current files to cloud
- [x] reference cloud files in code

**Comment by danalexilewis** [comment]
@ahdinosaur I’ll add [mailjet](https://www.mailjet.com/mailgun/) to the list. Which uses [mailjet markdown language](https://mjml.io) - which makes custom email templates suck less. Though you could use mjml without mailjet.

I’d add that sendgrid and mailjet have campaigns which may be helpful while mailgun and mandrill will need to be used with mailchimp (I think)

Anyway - I’d say ease of dev is one of the most important measures. Campaigns and business process interoperability come second.

**Comment by ahdinosaur** [comment]
@agentlewis i think it'd be best to use [Catalyst Cloud](http://catalyst.net.nz/catalyst-cloud) as our cloud provider, to start with hosting our large files. do we have an account with them already? if not, should i just make an account?

**Comment by ahdinosaur** [comment]
oops, ignore that last comment, i forgot i already made a Catalyst Cloud account for Root Systems. :sweat_smile:

**Comment by ahdinosaur** [comment]
most things are done, but for some reason https://github.com/root-systems/cobuy/commit/31354ffef392d0c5820f6514925b221148974bbb caused the styles to break terribly wrong on both production and development, trying to figure out why.

**Comment by ahdinosaur** [comment]
oh hey, upgrading the dependencies fixed all the things. also why they broke, yay magic.

**Comment by ahdinosaur** [comment]
https://cobuy.tapin.nz/ is mostly working, but styles are now broken again in a _different_ way. :roll_eyes:

**Comment by ahdinosaur** [comment]
okay, sorted this out in https://github.com/root-systems/dogstack/pull/83 and https://github.com/root-systems/cobuy/pull/209, https://cobuy.tapin.nz/ is now working.
