### ISSUE TITLE
prepare for Tapin demo on Oct 25

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#186]
- public on 25th
- to Meghan is 27th

**Comment by danalexilewis** [comment]
Show progress (the app)
Show how we work

TODO:

 - [ ] slide of burndown chart
 - [ ] slide of waffle and ticket detail

**Comment by ahdinosaur** [comment]
group huddle @root-systems/cobuy 

- [x] detailed outline for demo flow with mock data: #207 @iainkirkpatrick 
- [x] sweet through app and create tickets for bugs, polish, etc @iainkirkpatrick, @Julietbc 
- [x] review pull requests
- [x] i18n missing (need ticket for this)
- [x] group supplier admin dropdowns don't display selected option (need ticket for this)
- [x] deployment #185 @ahdinosaur
- [x] casting intent #218 
- [x] order summary @NotThatSmith 
  - [x] per-product summary for supplier
  - [x] per-agent summary for consumer
- [x] start screen recordings!
  - [x] find good screen recorder: quicktime on mac, [kazam](https://launchpad.net/kazam) on linux
  - [x] find good video editor: ??? on mac, openshot on linux

**Comment by iainkirkpatrick** [comment]
done wooh!
