### ISSUE TITLE
clicking back changes the url but doesnt refresh content

### ISSUE THREAD

**Issue by danalexilewis** [root-systems/cobuy#196]
tested in dev:

given I have opened localhost:3000
and I am not logged in
and I seed the splash page with sign in and register
and I click register/signup
and am taken to the corresponding form
When I click the browser back button
then the url changes
but not the content

browser: chrome
os: linux

**Comment by iainkirkpatrick** [comment]
[this thread](https://github.com/ReactTraining/react-router/issues/5072) i suspect may be talking about the same bug, with some suggested workarounds (react-router-redux v5 is in beta)
