### ISSUE TITLE
create clear source of truth for milestones

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#197]
- what is in scope for each milestone?
  - job stories
- what deadlines are upcoming?
  - customer expectations

**Comment by danalexilewis** [comment]
had a punt at it:

Cobuy needs to facilitate two primary user stories through the application ~~~ 

(((((Admin))))) sign up —> setup user profile —> setup group —> add group user emails —> add supplier —> open order —> invite users —> close order —> approve order for sending to supplier —> send email 

(((((Group user))))) receive invite —> sign up —> setup user profile —> intent cast in order —> see summary of order —> order sent —> invoice received —> order updates

unfortunately milestones dont allow markdown.... https://github.com/root-systems/cobuy/milestone/9

**Comment by danalexilewis** [comment]
@Julietbc @iainkirkpatrick @NotThatSmith @ahdinosaur keen for some group thinking/editing on this.

**Comment by danalexilewis** [comment]
ok I have updated this to use some emoticons to make it easier to read. I think this is the best place for it. Happy to add/iterate it in the next sprint after I get feedback :P
