### ISSUE TITLE
Close an order

### ISSUE THREAD

**Issue by michael-smith-nz** [root-systems/cobuy#210]
A few possible ways of an order closing

- Time-based -  when an order end date is reached that order is considered closed.
- Manually close - An admin must manually press a button to close the order
- Something else?

In the future, we'll need to add some form of 'hooks' (send email, create tasks, etc) when an order is closed.

**Comment by ahdinosaur** [comment]
one way is we store the "status" on the order object: https://github.com/root-systems/cobuy/issues/21. the problem with this approach is that there are actually so many possible statuses, and this way we lose provenance (records of the flow) between statuses.

another way is that when an order is closed, we create the order plan. this means an order is "closed" when the order plan is created. the order intents can be "locked" either implicitly through this or explicitly.

or maybe a hybrid approach is we add a property to the order `intentsClosedAt` which is a timestamp for when the intents casting phase is closed.

**Comment by michael-smith-nz** [comment]
Notes:

- What's the UI workflow? Could have the admin manually pressing a button to close an order for now? Where would this live?
  - This will complete/close all 'Add items to this order' tasks (create taskworks)
- Should be easy in the future to move from a manual close to a time-based closed
- When an order starts an admin could have a 'close order' task show on their dashboard


- A Closed order is an order with an OrderPlan associated with it.

**Comment by michael-smith-nz** [comment]
TODO:

- When an order is created, add a `close order` task plan assigned to the admin of the order
- When the order is closed make sure all `cast intent` task plans associated with that order are closed (create task works for them?)
- When order is closed, make order summary available to view (work could be done in #214 instead)

**Comment by danalexilewis** [comment]
Just to add some other ways an order might close:

- money based (a certain amount has been reached)
- participation based (a certain number of buyers)
- a number of items (say 50 chrome books)

These could maybe be combos to. Like a money and participation requirement.

We could also open an identical order as a result of this close (out of scope for this ticket - just context). The 50 chrome books is a good example. Let’s say every time we reach 50 it closes and opens a new one and invites the same participants to it (like a follow this order feature)

**Comment by michael-smith-nz** [comment]
Thanks Dan, that might be good to document in the wiki as well.

I think at this point I'd appreciate you wearing the product owner/person closest to end users hat and letting us know what would be the most useful way for users to close an order. Is the way I was thinking above the best, or is one(or many) of the ways you suggested best?

If we need all of them this might need some more thinking before we get into coding more.

-------- Original Message --------

**Comment by danalexilewis** [comment]
Sorry @NotThatSmith I should have been clear that was an info bomb of options and mvp would definitely be a manual close button the order admin can use.

Cheers for the call to action
