### ISSUE TITLE
Refactor ordering journey copy

### ISSUE THREAD

**Issue by Julietbc** [root-systems/cobuy#212]
- update 'My Profile' to 'Group Profile' in set up group profile
- update 'My profile' to 'supplier profile' in set up supplier profile
- fix edit product button

**Comment by iainkirkpatrick** [comment]
@Julietbc - was just cruising the tickets and notice I updated the first two points today in a different ticket - [PR here](https://github.com/root-systems/cobuy/pull/217) your review welcome!

**Comment by iainkirkpatrick** [comment]
these are done now :)
