### ISSUE TITLE
remove the tickbox from invite members list

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/cobuy#234]
why would we ever untick this during this task

**Comment by ahdinosaur** [comment]
what tickbox?

**Comment by ahdinosaur** [comment]
ohh, this tickbox:

![screenshot_20171101_175204](https://user-images.githubusercontent.com/719605/32260542-6760d582-bf2d-11e7-82ca-90cae59f5834.png)

it's actually a `isAdmin` checkbox. my idea was to allow people to specify roles through a simple checkbox system, but yeah at the moment it's pretty lame and the only role we have implemented is admin.

keen to revisit this in #148?
