### ISSUE TITLE
bug: inviting a member bails on a table insert error

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/cobuy#235]

**Comment by ahdinosaur** [comment]
what's the error?

**Comment by iainkirkpatrick** [comment]
a FEATHERS_AGENTS_ERROR with message "update "agents" set "consumerAgentId" = 3, "type" = 'person' where "id" = 2 - SQLITE_ERROR: no such column: consumerAgentId"

this is because `consumerAgentId`is being passed in with the data when creating an agent when inviting members. though just tested and this is fixed in an [open PR](https://github.com/root-systems/cobuy/pull/211) i have, so i'm gonna close this issue for now.
