### ISSUE TITLE
Logout button does nothing

### ISSUE THREAD

**Issue by michael-smith-nz** [root-systems/cobuy#245]

**Comment by ahdinosaur** [comment]
@iainkirkpatrick didn't you fix this recently?

**Comment by ahdinosaur** [comment]
ah yeah: https://github.com/root-systems/dogstack-agents/pull/17

merged that pull request, published a new version of `dogstack-agents`, and pushed a commit to Cobuy to upgrade to latest `dogstack-agents`.
