### ISSUE TITLE
first pass at user activity flow diagram

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#25]
will involve making diagram into a digital flow chart which captures all the possible user activities

**Comment by sarah-arrrgh** [comment]
Flow chat link:
https://www.draw.io/#G0B9Qp9qMj9fuyWFJvOHNsSzVyWDA

**Comment by sarah-arrrgh** [comment]
![image](https://user-images.githubusercontent.com/12442114/27310005-44aeb108-55ab-11e7-80dd-bc33669bd809.png)

**Comment by danalexilewis** [comment]
@sarah-arrrgh how's the drawing coming?

**Comment by sarah-arrrgh** [comment]
**FLOWS**

**Sign up**

- [x] Sign up as someone who wants to create/admin a new group
- [ ] Sign up as someone who has been invited to join a group as a member - still in pre-requisite phase
- [ ] Sign up as someone who has been invited to join a group as a member - past pre-requisite phase
- [ ] Sign up as someone who has been invited to help admin a new group - still in pre-requisite phase
- [ ] Sign up as someone who has been invited to help admin a new group - past pre-requisite phase
- [ ] ?? Sign up as someone who doesn't yet belong to a group and doesn't want to be an admin

---

**Log in**

- [ ] Log in as a member of an already established group
- [ ] Log in as an admin of an already established group
- [ ] Log in as a member of a group in the pre-requisite phase
- [x] Log in as an admin of a group in the pre-requisite phase
- [ ] ?? Log in as someone who doesn't yet belong to a group and doesn't want to be an admin

---

**Pre-requisite phase**

- [x] Create my profile
- [x] Edit my profile
- [x] Create group profile
- [x] Edit my group profile
- [ ] ?? Create another group before the first is finished
- [x] Invite members to a group via CSV
- [x] Invite members to a group manually
- [x] Invite admins to a group via CSV
- [x] Invite admins to a group manually
- [x] Edit member/admin list of my group
- [x] Add first supplier profile
- [x] Add supplier product info via CSV
- [x] Add supplier product info manually
- [ ] ?? Add another supplier before the first is finished
- [x] Once all three pre-requisites are completed, take user to main dashboard

---

**Member dashboard - ORDERS**

- [ ] View open orders
- [ ] Place an order
- [ ] Edit my order
- [ ] Delete my order
- [ ] View all suppliers
- [ ] View supplier details
- [ ] View product list of a supplier
- [ ] View my favourite products of a supplier
- [ ] Suggest a new supplier
- [ ] View a closed order I participated in
- [ ] See order status for all current orders (all open, closed orders I participated in)
- [ ] View my tweaked order (what I will receive if what we send to the supplier arrives)
- [ ] View my order history
- [ ] View all favourite products across all suppliers (??)
- [ ] View when the next order for a certain item is

---

**Member dashboard - GROUP**

- [ ] View my profile
- [ ] Edit my profile
- [ ] Delete my profile/account
- [ ] View all groups I am part of
- [ ] Leave a group
- [ ] View contact details for group members
- [ ] Add someone to waitlist (invite someone to group)
- [ ] Delete someone I invited on the waitlist
- [ ] Contact other group members (??)

---

**Admin dashboard - ORDERS**

- [ ] Add new supplier
- [ ] Edit existing supplier
- [ ] Delete supplier
- [ ] Start an order
- [ ] Edit an order
- [ ] 

---

**Admin dashboard - GROUP**

- [ ]

**Comment by ahdinosaur** [comment]
@sarah-arrrgh this is really great, i appreciate the format and level of detail. :heart_eyes_cat:

**Comment by sarah-arrrgh** [comment]
Checklist now lives here:
https://github.com/root-systems/cobuy/wiki/User-activity-flows
