### ISSUE TITLE
infinite loop of taskworks loading on dashboard

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/cobuy#258]
i think it's something like this - iain to investigate

**Comment by ahdinosaur** [comment]
is there a work-around for this? i'm not sure how to get to the intent casting page with this, halp. :cat:

**Comment by iainkirkpatrick** [comment]
not yet @ahdinosaur - i'm unsure how we should fix it, the seeded agents don't have `createProfile` tasks which the current code assumes is there (i.e. always at least one taskPlan). bad assumption i know. what else to put in the `Dashboard`'s `shouldQueryAgain` though?

**Comment by iainkirkpatrick** [comment]
I can look at this after football if need be

**Comment by ahdinosaur** [comment]
there's always a way, i think i can sort something out using the `status` object.
