### ISSUE TITLE
bug: configuring order doesn't show available groups, suppliers, admins unless refreshed

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/cobuy#281]
as per title - to show the seeded data, for instance, requires a refresh

**Comment by ahdinosaur** [comment]
hey @iainkirkpatrick, do you estimate this as easy, medium, or hard? if not easy, i think we should punt and focus on #270 instead. what do you think?

**Comment by iainkirkpatrick** [comment]
@ahdinosaur my sense is this will probably be easy - just a missing query somewhere (by missing i mean a query that is triggered on app refresh, but not by following the order setup through) - but I think #270 is legit and keen to see that happen, so if you want to jam on that I reckon go for it and we'll park this. If you aren't doing that yourself, if I was doing this I'd try and get this one done quick, then do #270.
