### ISSUE TITLE
switch local dev to use postgres rather than sqlite

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/cobuy#289]
using sqlite for local dev has been easy, but now we have production / staging deployments which use postgres, we are encountering some bugs / crashes when deploying due to the differences between sqlite and postgres.

this ticket is to change connection config to postgres, along with a guide to getting cobuy running locally on MacOS / Linux.

**Comment by ahdinosaur** [comment]
nice! can we re-use https://dogstack.js.org/guides/how-to-setup-sql-db.html? i did that a while ago, maybe useful idk.

**Comment by iainkirkpatrick** [comment]
ooooh yeah that looks good @ahdinosaur :) i can fill out the mac user part (tho there isn't much more to it than postgres app)
