### ISSUE TITLE
intent -> commitment resolution algorithm

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/cobuy#297]
this ticket is for cleaning up / making clear the algorithm that resolves a groups order intents into a set of order commitments for an order

this logic is used both in hooks when an order closes (intents -> plans) and on the client when displaying the current commitment state of each product in an order

**Comment by danalexilewis** [comment]
@iainkirkpatrick Is there an update for this ticket? Where is it at?

**Comment by danalexilewis** [comment]
Also how big is this - last week the update was that it was basically done. What is the estimate on this work?

**Comment by iainkirkpatrick** [comment]
Update is working on it right now: the logic appears to be working for the client (i.e. for the list of products, show the correct price and group quantity per product), i'm now working on getting it going on the server (for when an order closes to actually generate the finished orderPlans).
Currently running into a problem where it looks like how we determine the `currentOrderId` is built for the client, need to figure out how to use it on the server properly...

My guess is a couple more hours, if i can suss this problem it **should** just work

**Comment by iainkirkpatrick** [comment]
oooh just got it all working :) needs a bit of testing but looks good i think!

branch is `product-list-realtime-updates` (old name but covers both client and server now)
