### ISSUE TITLE
intuit the ux

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#298]
this ticket is to take a minimal viable set of changes from https://github.com/root-systems/cobuy/issues/157 that can make the ux more intuitive

**Comment by danalexilewis** [comment]
So what are the proposed changes? I saw a bunch of drawings - but it’s unclear what’s been done and what has yet to be done. How big is this ticket?

**Comment by ahdinosaur** [comment]
first-pass done in #313
