### ISSUE TITLE
rebrand tapin deployment to tapin:buy

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/cobuy#299]

**Comment by ahdinosaur** [comment]
most of the heavy lifting for this has already been done in #273, so should be as easy as changing a single environment variable in the heroku app.

**Comment by ahdinosaur** [comment]
@agentlewis should this include changing the domain to `buy.tapin.nz`?

**Comment by danalexilewis** [comment]
Yeah - though Lauren (new coms peep) may have is change it again ;)

**Comment by danalexilewis** [comment]
It will also involve changing the colours to match the other sites.

**Comment by danalexilewis** [comment]
link to colour palette https://drive.google.com/file/d/0B-3EqhzOmCyzZ2pwY3dWdHFEVWs/view?usp=sharing

**Comment by ahdinosaur** [comment]
first-pass done with #314, will need to check how this lands in production
