### ISSUE TITLE
View 3 current orders

### ISSUE THREAD

**Issue by danalexilewis** [root-systems/cobuy#3]
When I have entered the app, I want to see a list of three current orders, so that i can see that i can participate in multiple orderz

**Comment by ahdinosaur** [comment]
![cobuy-orders-page](https://cloud.githubusercontent.com/assets/719605/24085552/3fb82a02-0d63-11e7-94d5-68a4cfc1b858.jpg)

**Comment by ahdinosaur** [comment]
first pass done! https://github.com/enspiral-root-systems/cobuy/commit/2e47df8875c1143f2e28051e18d33a07b5c19b0c

![snapshot137](https://cloud.githubusercontent.com/assets/719605/24089097/4303bc10-0d97-11e7-8c34-c0315a622955.png)

**Comment by danalexilewis** [comment]
mikey that looks great!
