### ISSUE TITLE
page: pre-requisites

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#31]
view nested Task\* data models as a checkbox list, similar to a nested trello card

- [ ] paper sketch (upload photo)
- [ ] dumb component (maybe add to storybook)
- [ ] make it work with the app

**Comment by ahdinosaur** [comment]
question: how does the "task" represent the flow across pages? for example, the "create my group" sub-task involves going to the group profile update page, then the invite members page, then the task in complete and they go back to the pre-requisites page.

**Comment by danalexilewis** [comment]
Id say an atomic task is something that is or is not complete. ie it cannot be partially completed. I think this is the definition of a workflow - a series of tasks. Where a workflow can (if desired) be partially complete - chached to be completed later.

So when I read task above I actually think its a workflow of a series of tasks (actions) across multiple pages.

Not sure if that sheds some light on this. And noting it was 25 days ago...
