### ISSUE TITLE
'Cancel' and 'Done' button on all tasks navigate back to dashboard

### ISSUE THREAD

**Issue by michael-smith-nz** [root-systems/cobuy#318]
Expected to navigate one step back, rather than to root.

![cancel](https://user-images.githubusercontent.com/1152577/34106679-08d353ee-e3f1-11e7-8f95-5bcace8aa289.gif)

**Comment by michael-smith-nz** [comment]
unsure about the 'done' button. Only happened to me once. But cancel happens all the time

**Comment by ahdinosaur** [comment]
yeah, i noticed this, but wasn't sure how to solve it. we need a way to know where the user came from, so we know how to take them back to the right place. until now, the only place you could click on a task was the dashboard, so it was an easy hack. now this right place could either be the tasks page, the orders page, or an order page.

**Comment by michael-smith-nz** [comment]
@ahdinosaur Could we use the `history` api on our router? https://reacttraining.com/react-router/web/api/history
