### ISSUE TITLE
page: create my profile

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#32]
- [ ] paper sketch (upload photo)
- [x] dumb component (maybe add to storybook)
- [x] add it to `dogstack-agents`
- [ ] make it work in the app

needs to be a personal task assigned when someone registers as a new user.

closes #140

**Comment by sarah-arrrgh** [comment]
End of day report:

- made a (temporary) button on the dashboard to create a create profile task plan. wired it all up magically.

TODO: 

- [ ] fix git lfs thing with @ahdinosaur 
- [ ] wire up view/edit profile component
- [ ] probably other things... @iainkirkpatrick ?

**Comment by sarah-arrrgh** [comment]
TODO Thursday arvo:

- [x] set up props for CreateProfileTask Container/Component to go through to Profile component
- [ ] add more fields to the person profile 
- [ ] convert button to hook

**Comment by sarah-arrrgh** [comment]
End of day report:

- generic Profile component rendering as the component of a CreateProfileTask
- looked at adding more fields to the Profile for a Person, but decided in consultation with @ahdinosaur that it'd be good to have deliberate design on which fields make sense before developing
- investigated how to add a hook to `dogstack-agents` for creating the CreateProfileTask after a Person is created - needs more work

TODO:
- [ ] chat to Mikey more about hooks on `dogstack-agents`
- [ ] if iain gets a chance to try more hooks work, then explain to sarah on Monday what progress has been made

**Comment by iainkirkpatrick** [comment]
got a hook working tonight - will solicit feedback tomorrow / monday :)
