### ISSUE TITLE
fix font

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#329]
![Screen Shot 2017-12-19 at 8.23.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/554158c23ae54b6500e6c8b0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fa6b7191a370f110284f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ee5833b5772c03c16aeb8d617b902be208b4784e4e98e1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df748e74b5da6173665ee7f2431.png)

**Comment by iainkirkpatrick** [comment]
had a quick look at this - not sure how to solve though.
looks like we are loading the fonts incorrectly - https://github.com/rofrischmann/fela/blob/master/docs/api/fela/Renderer.md#renderfontfamily-files-properties

i.e. not providing a link with the correct font extension? but it's unclear from Google how to do that with Google Fonts?
did using fonts in this way ever work?

**Comment by ahdinosaur** [comment]
>  did using fonts in this way ever work?

no, see #171

**Comment by ahdinosaur** [comment]
@iainkirkpatrick maybe try a more rugged approach using [`webfontloader`](https://github.com/typekit/webfontloader) or just plain `document.createElement('link')` etc?

**Comment by iainkirkpatrick** [comment]
wait, is this actually not working? cause this title is Lobster font right?

![screen shot 2017-12-20 at 11 46 54 am](https://user-images.githubusercontent.com/1994975/34185794-86ae2e3e-e57b-11e7-80b4-88274d731be4.png)

other solution is to just have the font files as assets right? host them on catalyst same as other assets?

**Comment by ahdinosaur** [comment]
it doesn't work on Linux, gives a clear error even on macOS where it works, so i'm not sure how well it works on other platforms.

**Comment by iainkirkpatrick** [comment]
ok, had a play with `renderer.renderFont` with downloaded fonts, can't work out a good way to load multiple weights of the same font though... (tried naming each variant it's own 'family', but this means the `font-weight` property can't be used a standard way)

so for now, just a `<link>` element in the bundler in `default.js`, this works
