### ISSUE TITLE
inviting existing users will result in infinite loop

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#347]
consider alongside #472

**Comment by danalexilewis** [comment]
@gregorykan is this the bug that breaks everything?

On the morning of the last showcase the other tapin peeps had done something and all the profiles disappeared and I could no longer create the order summary.

I suspect they invited themselves again or something as they were struggling to login.

**Comment by iainkirkpatrick** [comment]
my guess is it bails trying to create a user with the same email as an existing user... so
- prevent that
- don't create a JWT for a user if they already exist when invited to a new group, just send them some generic email saying "hey, you've been invited to a group, log in and check that out"

**Comment by gregorykan** [comment]
- check if agent and credential already exist
- if they do, create the new relationship
- write and return context.result accordingly (https://docs.feathersjs.com/api/hooks.html#contextresult)
