### ISSUE TITLE
app crashing after trying to add intent

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#350]
- sometimes price specs are not retrieved properly
- error being thrown from same getter, `ordering/getters/getCurrentOrderCollectiveQuantityByProduct.js`

**Comment by iainkirkpatrick** [comment]
aha! think i know what this is - repro'd it locally by casting an intent on an order that doesn't meet the minimum priceSpec, and I notice this is the same situation as Greg's experience on production (3 intents cast, each for a separate priceSpec, none meeting the minimum).

will fix.
