### ISSUE TITLE
summary of known issues for 21/12 demo

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#351]
@agentlewis, this is a summary of persistent known issues that may present themselves during the demo:

1. if you invite someone whose email is already registered on the database, the app will enter an infinite loop. (see #347)

2. if you logout of an existing account, and register a new one, orders you create with the new user may not show up as there is some weird issue with leftover/residual state from the previous user. if you or anyone else wants to register multiple users, just be sure to hard refresh after logging in with the new user. (see #346)

3. if you want to close an order after having added intents, you have to click on the 'commit' stage. there will be a 'commit order' task there. inside this task is a sub-task to 'close order'. after completing the 'close order' task, you should be able to view the order summary.

4. sometimes adding intent fails, after adding a product and price specs. @iainkirkpatrick is currently investigating this. it does not happen consistently and when i left the office we were unsure of its conditions. this can also lead to an infinite loop. i'd recommend creating a new product and avoiding adding the problematic product in your intents if this happens. if that fails, the worst case scenario is creating a new supplier with new products. (see #350)

**Comment by iainkirkpatrick** [comment]
nb. 4. is fixed with #352 :)
