### ISSUE TITLE
order creator modal not loading properly

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#357]

**Comment by ahdinosaur** [comment]
Dan: (maybe) happened when logged in, changes have been pushed, but haven't refreshed the app. logged out, refreshed, logged in and it worked. maybe to do when state is still in the app, maybe when changes were pushed when page last loaded.

Mikey: could be that we fixed this bug at the last moment?

TODO replicate bug

**Comment by gregorykan** [comment]
i can't replicate this, but will continue to keep an eye out, especially when testing production next. closing for now as it seems likely that we fixed this.

**Comment by gregorykan** [comment]
ok, this happens very infrequently but i haven't figured out why yet

**Comment by gregorykan** [comment]
may be connected to #424
