### ISSUE TITLE
page: add products and prices

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#36]
depends on https://github.com/root-systems/cobuy/issues/114 being done first.

job story: when i want to setup my the supplier for my first order, i can add products (offerings) and corresponding prices (price specifications).

![screenshot_20170816_144549](https://user-images.githubusercontent.com/719605/29345254-9be7896e-8291-11e7-9a9a-81f2576c3756.png)

will be a similar implementation to https://github.com/root-systems/cobuy/pull/120, possibly done in parallel with https://github.com/root-systems/cobuy/issues/34.

**Comment by danalexilewis** [comment]
@Julietbc is this complete?
