### ISSUE TITLE
should have hints/guides everywhere on the app

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#365]
- tooltips to start with
- this ticket is just to get us started

**Comment by ahdinosaur** [comment]
can do simple tooltips with [IconButton](http://www.material-ui.com/#/components/icon-button)

if this isn't enough, we can use [Popover](http://www.material-ui.com/#/components/popover)

**Comment by danalexilewis** [comment]
The icon Button solution would rely on us having a set of icons that people intuitively know. I ha e a feeling pop over with text will be easier - ie we just write what we want

**Comment by ahdinosaur** [comment]
@agentlewis i'm not sure i understand what you mean. i was thinking we'd use a "help" looking icon button in either case, the only difference is whether we use the browser tooltip or pop open a full html element. do you want to draw a picture or something to describe the interaction you expect?

**Comment by danalexilewis** [comment]
@ahdinosaur your or cleared it up for me - for some reason I thought the icons would be the hints... Which is actually not a hint at all and is just good ui. So anyway - I like where your taking this.
