### ISSUE TITLE
name used in registration not being used elsewhere

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#370]
for example, the name is not populating as part of the profile

**Comment by iainkirkpatrick** [comment]
looks like this is because an agents Profile isn't updated correctly when registering, looking at it now

**Comment by iainkirkpatrick** [comment]
hmmm, this should be straightforward but getting a strange error... if the Profile service gets given 'name' data, now there's a 'constraint violated' postgres error on the agents table. not sure why...

**Comment by iainkirkpatrick** [comment]
fix for this issue is in `dogstack-agents` [here](https://github.com/root-systems/dogstack-agents/pull/23)
