### ISSUE TITLE
product intent component improvements

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#377]
- on intent page,
  - everyone had to clearly read text, kinda understood, maybe
  - unclear that there was a text input
  - didn't realize you could enter at multiple price points
  - need to communicate
    - what to do on a fixed volume order
      - fix volume @ 1 price, whatever it is -> cheapest unlocked
    - what to do on a fixed budget order
      - fixed budget, get max volume, at price point unlocked
     - what to do on an opportunistic order
       -  'i only want to buy if it's at the cheapest price point'

**Comment by ahdinosaur** [comment]
![cobuy-intents](https://user-images.githubusercontent.com/719605/33533114-e17131d8-d903-11e7-9387-45982ae3d018.png)
