### ISSUE TITLE
page: individual intent casting

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#39]
depends on https://github.com/root-systems/cobuy/issues/44 and https://github.com/root-systems/cobuy/issues/49.

job story: when my group is ready to begin an order, i should be assigned a TaskPlan to cast my individual intent, where i can say my { desired, minimum, maximum } values for how much i want to order for each product offered by the order supplier given the price specifications. 

branch: `feature/page-individual-intent-casting`

**Comment by sarah-arrrgh** [comment]
TODO:

- [x] wire up the component to a page with a route
- [x] on dash, add another active task `cast your intent for order x` after an order has started
- [x] figure out how complete the intent casting component is

**Comment by sarah-arrrgh** [comment]
**Services and hooks**

Compared with FA, we didn't develop the backend, we just used API routes that Sebastian built for us to interact with the database.

On Cobuy, Dogstack uses Feathers to generate and manage our API.
Feathers - service. Service refers to a collection of API routes for doing CRUD of a topic*, so we end up having an agent service and a order service etc.
e.g. if we want to create an order, we use the order service, and call .create on it if we want to 

**[Hooks](https://docs.feathersjs.com/api/hooks.html)**
If you have a basic service, you can attach hooks to that service. Hooks = functions that run either before a service attempts an operation (CRUD), or after it's successful, or if it errors.

---

*topic = a thing, like an order or an agent. FA = domain

CRUD = CREATE, READ, UPDATE, DELETE
Feathers READ = FIND or GET
Feather DELETE = REMOVE
https://docs.feathersjs.com/api/services.html
```
const myService = {
  find(params) {},
  get(id, params) {},
  create(data, params) {},
  update(id, data, params) {},
  patch(id, data, params) {},
  remove(id, params) {},
  setup(app, path) {}
}

app.use('/my-service', myService);
```

**Comment by sarah-arrrgh** [comment]
syntax for reduxForm / higher-order components:

```
const higherOrderComponent = (component) => {
  const nextComponent = (props) => {
    return h(component, props)
  }
  return nextComponent
}
```

**Comment by sarah-arrrgh** [comment]
examples:

```
function doubleFunction (fn) {
  return () => {
    return fn() * 2
  }
}

const four = () => 4
const eight = doubleFunction(four)
const eight = () => doubleFunction(four)()
```

**Comment by sarah-arrrgh** [comment]
Status report:

- hard-coded avocado offering into CastIntentTask component - need to update with actual supplier offerings once #36 is completed
- wire up handleSubmit
- how to put order name into locales file (currently "cast your intent for order x" hardcoded in)

**Comment by sarah-arrrgh** [comment]
Thursday things:

Dan and Mikey met yesterday to discuss the Tapin/Cobuy relationship, and what exactly Tapin needs Cobuy to do. This lead to a change in plan that affects this ticket, whereby we no longer want a user to order using min/desired/max, as schools will be buying in whole outers already (so outers won't need to be split && orders wont need to be tweaked).

TODO:

- [ ] unwire the current min/desired/max intent casting component
- [ ] hook up a new intent casting component (likely displaying a list of available products and prices

**Comment by sarah-arrrgh** [comment]
@ahdinosaur 
keen to get your opinion on where to go exactly with this ticket. wondering if it might be blocked by #36?

**Comment by ahdinosaur** [comment]
hey @sarah-arrrgh, re-opening https://github.com/root-systems/cobuy/issues/49#issuecomment-324493824 for you. i think it makes sense to re-implement that component given the new requirements as a standalone task, then doing this task would be creating a list using this components given the available products.

**Comment by ahdinosaur** [comment]
> wondering if it might be blocked by #36?

@sarah-arrrgh it shouldn't be. we can assume that the products have already been creating according to the documented [data model](https://github.com/root-systems/cobuy/wiki/Models), which you can mock using fake data for now.

**Comment by sarah-arrrgh** [comment]
dependent on #49 to continue with this

**Comment by sarah-arrrgh** [comment]
End of day report

- finished intent casting components in storybook, including rendering price point sub-component
- fixed castIntent hook after rebase

TODO

- [x] wire up single product view component into intent casting page
  - task recipe specifies which component renders (change container or tell container to render different component)

Blocks:

- need Juliet's branch - product list creation for a supplier #36 
- need Iain's branch - starting an order #41

**Comment by iainkirkpatrick** [comment]
IMO this is done for now - we can extend the intent casting flows with other tickets, but the core is there
