### ISSUE TITLE
Add profile button to top right that opens an account menu

### ISSUE THREAD

**Issue by danalexilewis** [root-systems/cobuy#405]
Currently we have no place to put a link to a page to edit your profile, change your password etc...

**Comment by danalexilewis** [comment]
Gregs suggestion for a quick fix was to just put this in the existing nav

**Comment by iainkirkpatrick** [comment]
there are no routes for these pages (edit profile, change password) yet right? though we have some existing componetry we could borrow

**Comment by ahdinosaur** [comment]
> there are no routes for these pages (edit profile, change password) yet right? though we have some existing componetry we could borrow

correct, that's the scope of work for this ticket.

**Comment by gregorykan** [comment]
duplicate of #456
