### ISSUE TITLE
(Admin) Add the supplier and products before members 

### ISSUE THREAD

**Issue by danalexilewis** [root-systems/cobuy#409]
Currently when the members received their invites there was nothing in the order as the supplier and products had not been created yet. 

Rather we should add the supplier and products before this step so that everything is ready for when the members are invited.

**Comment by danalexilewis** [comment]
Users are clicking  the link in the email when there is nothing there yet

**Comment by gregorykan** [comment]
@ahdinosaur suggested triggering invitation emails on start order

- members still persisted on form submit, only email hook moves to order start
- email type 1: not logged in before, set password, link to first order
- email type 2: logged in before, link to next order
