### ISSUE TITLE
review names/terms/copy

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#430]
goal to have consistent, clear vocabulary that we use and that is reflected in the codebase as well as the UI copy

**Comment by gregorykan** [comment]
- invitation email will need a sit-down revision:

```
        Hi. You're invited to join a group on Tapin!

        Cobuy is an app that makes buying groups easy to start, maintain, and grow. Using the collective buying power of a group, we can buy food in bulk directly from wholesalers. By cutting out retailers, we effectively eliminate retail food waste, save money and have access to a wider range of better quality products.

        Click <a href=${hook.app.get('app').url}/invited/${token.jwt}>here</a> to set your password and start buying together!
    
```

**Comment by gregorykan** [comment]
Order Stages:

- Setup -> Setup Order
   - Share intents to buy! The Intent stage is where each group member decides how much of a product they want for each price point -> ????
- Intend -> ?????
- Commit -> Confirm

**Comment by gregorykan** [comment]
Add Item to Order Page:

- should show whole price range, i.e. both lower and upper limit
- "if everyone orders more than 10, then this item will cost 10 nzd each, in which case, I want to order" -> ?????

**Comment by gregorykan** [comment]
Tooltips:

- "ordering.whatIsAnOrder": "An order is a group buying process with many stages: setup, intend, commit!"
 - "ordering.whatIsCurrentPrice": "The current price given the quantity the group has ordered so far"
 - "ordering.whatIsCurrentQuantity": "The current quantity the group has ordered so far for the current price"
-  "ordering.whatIsSetup": "The Setup stage is where the group admin enters prerequisite information on their buying group and supplier"
- "ordering.whatIsIntent": "The Intent stage is where each group member decides how much of a product they want for each price point"
- "ordering.whatIsCommit": "The Commit stage is where the group admin confirms and commits the group order"
 - "ordering.whatIsAPricePointIntent": "Specify how much/many of the product you'd want at this price point"
 - "ordering.setupStageDescription": "Setup details and start order."
 - "ordering.intentStageDescription": "Share intents to buy!"
 - "ordering.commitStageDescription": "Close an order, combine individual intents and commit to a purchase order ready to send to a supplier. Your group will no longer be able to go through the Intent phase."

**Comment by danalexilewis** [comment]
Suggestions for Intend:

 - draft (your order)
 - record (your order)
 - share (your order)
 - align 
 - list interest
 - fill cart 
 - stage / commit (it works for github ;)

**Comment by laurenshamy** [comment]
**Stages**

Setup Order
Draft Order
Confirm


**Product Order Page text:**

"If other members of this buying group order over 10 units, this item will cost $10 nzd each. If this price point is reached, I want to order: "


**Tooltips (new copy is written underneath orginal if changed):**

"ordering.whatIsAnOrder": "An order is a group buying process with many stages: setup, intend, commit!"

_"An "Order" is a group buying process with three stages: Setup, Draft and Commit!"_




"ordering.whatIsCurrentPrice": "The current price given the quantity the group has ordered so far"

_"The current price based on the quantity of product that the group has ordered so far"_


"ordering.whatIsCurrentQuantity": "The current quantity the group has ordered so far for the current price"

No change.


"ordering.whatIsSetup": "The Setup stage is where the group admin enters prerequisite information on their buying group and supplier"

_"The 'Setup Order' stage is where the creator of the buying group enters information about their intended buying group and supplier"_




"ordering.whatIsIntent": "The Intent stage is where each group member decides how much of a product they want for each price point"

_"The Draft stage is where each group member decides how much of a product they want for each price point"_



"ordering.whatIsCommit": "The Commit stage is where the group admin confirms and commits the group order" 

_"The Confirm stage is where the creator of the group confirms and commits the group to this order"_



"ordering.whatIsAPricePointIntent": "Specify how much/many of the product you'd want at this price point"

_"Specify how much/many of the product you'd want if the product was available at this price per unit"_



"ordering.setupStageDescription": "Setup details and start order."
No change

"ordering.intentStageDescription": "Share intents to buy!"
No change

"ordering.commitStageDescription": "Close an order, combine individual intents and commit to a purchase order ready to send to a supplier. Your group will no longer be able to go through the Intent phase."

_"Close an order, combine individual requests and confirm purchase. Order is now ready to send to a supplier. Your group will no longer be able to go back to "Draft" stage._

**Comment by laurenshamy** [comment]
**Invitation Email**

"Hi there!

 

You have been invited to join a buying group on Tapin!

 

**What does this mean?**


 

Tapin is a part of Cobuy - an app that makes buying groups easy to start, maintain, and grow. You've been invited to be a part of someone's buying group via this software.

 

 

**Why is group buying better?**

 

Buying collectively gives you the power to purchase products in bulk, directly from wholesalers. By cutting out the middle men, we promote efficiency, cut down on retail food waste, save money and have access to a wider range of better quality products.

 

 

**How do I get started?**
Click the link below to set your password and start buying together!

 

<a href=${hook.app.get('app').url}/invited/${token.jwt}>here</a>

 

Happy Group Buying!

Team Tapin"
