### ISSUE TITLE
Cannot see summary

### ISSUE THREAD

**Issue by danalexilewis** [root-systems/cobuy#434]
No matter what combination of closing the order i do I cant see a summary

**Comment by danalexilewis** [comment]
@gregorykan @ahdinosaur this is probably the current most critical issue

**Comment by gregorykan** [comment]
@agentlewis
![viewing-order-summary.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/554158c23ae54b6500e6c8b0/125516c66e82c728ace21e0d46fe9d9f348b8daec2e6ad47a14fbd873c4b2a723b1de1673295f127b54778154d555ca9490a094cfaff882ca4b668788c5f0fedd1655e26933947bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8e4a371602108ffa5b36a68b06.gif)

**Comment by gregorykan** [comment]
@agentlewis ok further update, can confirm this does not behave as expected on production

**Comment by gregorykan** [comment]
@agentlewis further further update - it DOES work as expected. i forgot to add intents the last time i tested this.
