### ISSUE TITLE
write tests for cobuying algorithms

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#452]

**Comment by iainkirkpatrick** [comment]
got basic deepEquality tests covering all the getters that make up the algorithm for intents -> plans (and representation of plans on the client before they're confirmed)... there are a few important other cases to cover in some of them, as well as unhappy paths perhaps?

**Comment by danalexilewis** [comment]
Iain can you size this ticket?

**Comment by iainkirkpatrick** [comment]
done. also not to self that the 'supply' domain getters used in the algorithms aren't covered yet
