### ISSUE TITLE
improve group management form/page

### ISSUE THREAD

**Issue by gregorykan** [root-systems/cobuy#472]
consider alongside #347

- [x] remove the auto-add-row feature
- [x] figure out why rows disappear and reappear and take forever
- [ ] make it so you can actually delete members

**Comment by gregorykan** [comment]
@ahdinosaur @agentlewis what are the requirements for this page?

**Comment by gregorykan** [comment]
no fixed requirements, with focus on improvements.

see #93

**Comment by iainkirkpatrick** [comment]
@gregorykan did you speak to @ahdinosaur @agentlewis ? are there no specific needs that this ticket is designed to address then? if so, i'd question if this ticket is necessary for the first deadline - if this is just a case of 'generally improve things'

**Comment by gregorykan** [comment]
@iainkirkpatrick understood! adding a couple of obvious things that would be worth implementing/correcting

**Comment by danalexilewis** [comment]
Yes as a feature this is not of high importance from my point of view - more something Greg indicated was causing general pain. Ie delivering this feature would solve some pain.

Note the remove doesn’t work once someone has been added - only for staging invites.

**Comment by iainkirkpatrick** [comment]
ok that helps clarify @gregorykan @agentlewis thanks :)
incidentally i think the reason rows take ages to reappear is cause we do a bunch of feathers service fetches after submitting... it's a case of optimising re-querying i think.

**Comment by gregorykan** [comment]
thanks @agentlewis ! then we will restrict the scope of this ~ i think the two points i added should be resolvable without too much cost

**Comment by danalexilewis** [comment]
@iainkirkpatrick alternatively we delay optimising such things in favour of a spinner showing its thinking. 

Than we could look at something like [redux offline](https://github.com/redux-offline/redux-offline) in dogstack
