### ISSUE TITLE
component: individual intent casting

### ISSUE THREAD

**Issue by sarah-arrrgh** [root-systems/cobuy#49]
creating the individual intent casting view so it can be tested and tweaked

https://github.com/root-systems/cobuy/issues/20

**Comment by ahdinosaur** [comment]
https://github.com/root-systems/cobuy/issues/20

**Comment by sarah-arrrgh** [comment]
TODO:

- [x] min, desired & max values correspond to a number scale passed in
- [x] min, desired & max relate to each other sensibly
- [x] if you move desired, min and max move
- [x] on initial click, set min to be \< desired and max \> desired
- [x] visual cues to show min+max - vertical lines, boxing in around desired
- [ ] style slider lines to be dashed

NICE TO HAVE:

- [ ] initial click > smooth transition to three sliders

**Comment by sarah-arrrgh** [comment]
Initial UI for member intent casting for a product:

![image](https://user-images.githubusercontent.com/12442114/27671397-9967c8cc-5ce7-11e7-8e6c-dc3f8efd52c2.png)

Three sliders with dashed lines:
Top slider = minimum
Middle slider = desired
Bottom slider = maximum

- On load, only middle slider (desired) is visible. (if a member doesn't want any of that item, we don't need to know that their min and max is also zero)
- On click, top and bottom sliders appear, with an auto min + max value applied (customised per item)
- Solid vertical lines show order range, left line = min, right line = max (unsure if these will be square brackets as in picture or simply vertical lines)
- On change of min or max, the order range changes size (i.e. the box grows/shrinks)
- On change desired, the order range remains the same size (unless it hits zero, then min will be zero and order range will shrink)
- Slider max value will default to some sensible number (decided by group admin for each product?), like 5kg of apples
- If member wants more that slider max value, they can drag the slider-dot to the max, hold it there,  and the slider max will increase. This would change the max for all three sliders.
- Can set a minimum tolerance/range for each product (e.g. if I want 2kg apples, the min tolerance is +-0.5kg)

**Comment by danalexilewis** [comment]
@sarah-arrrgh can you add some text explaining the image?

**Comment by danalexilewis** [comment]
Design questions for anyone:

 - why are there three sliders?
 - what does the box created by the verticle lines signify? A target? 
 - can I only move desired?
 - if on the initial click min is desired is there then nothing in the middle of the box?
 - what's the difference between min and desired?

Not expecting a change to what's being done - rather documentation of why we are doing it this way.

That way we have documentation to reference when we test via showing the dumb component to peeps via storybook.

**Comment by agentlewis** [comment]
Not expecting a change to what's being done - rather documentation of why we are doing it this way.

**Comment by sarah-arrrgh** [comment]
@agentlewis have added some notes to the photo comment, let me know if you are still unclear on anything!

**Comment by danalexilewis** [comment]
Great thanks

Design questions that remain unclear to me:

 - you added notes saying what the 3 sliders are, can you also explain why there are three and not one. Or something else entirely like fields, dials. Buttons etc. what is the desicion that led to there being 3.
 - it would be great if you do some ux testing of these sliders as soon as possible and see if it's intuitive what they are. Ie can people use it without direction. Storybook should make this easy. Maybe even render 3 sliders without the lines and see what peeps say and then with and see if it's different.
 - I still don't see what the difference between min and desired is. But see it as better to build in the feature of having it then not. Ie we can always make a type of item where min and desired are the same and it has a slightly different ui component. 

New things:

 - Given this is being computed in real time with other peeps how will I be shown what I am likely to get?
 - I see no numbers in the sketch are there meant to be some? If so where?

**Comment by ahdinosaur** [comment]
re-opening, since requirements have changed: https://github.com/root-systems/cobuy/issues/137#issuecomment-324489622

we no longer need `mininum` and `maximum`, so can be a single number and/or slider.

while updating this component, we should update to match [data model for Product, Resource Type, and PriceSpecification](https://github.com/root-systems/cobuy/wiki/Models).

**Comment by sarah-arrrgh** [comment]
TODO:

- [x] sketch out new intent casting components - both list/row view, and whole page view
- [x] make new components in storybook
- [x] create mock data for product
- [x] create storiesOf for different product cases in storybook (refer tasks/stories/TaskWorker)

**Comment by sarah-arrrgh** [comment]
research ticket #147

**Comment by sarah-arrrgh** [comment]
massdrop flow

<img width="1119" alt="screen shot 2017-08-24 at 5 04 42 pm" src="https://user-images.githubusercontent.com/12442114/29650324-7f9c059c-88ee-11e7-915b-cf6b766a77ea.png">

<img width="1118" alt="screen shot 2017-08-24 at 5 05 00 pm" src="https://user-images.githubusercontent.com/12442114/29650326-8382d8c0-88ee-11e7-8340-fd8b6f9214fd.png">

<img width="1112" alt="screen shot 2017-08-24 at 5 05 28 pm" src="https://user-images.githubusercontent.com/12442114/29650333-875c2e9c-88ee-11e7-97ca-a9b4bbe22907.png">

**Comment by sarah-arrrgh** [comment]
![20170906_140045](https://user-images.githubusercontent.com/12442114/30091140-0ecc1e1a-930c-11e7-8895-c39836c57418.jpg)

**Comment by sarah-arrrgh** [comment]
TODO:

- [x] make mock product data
- [x] scaffold product list component
- [x] scaffold single product component
- [x] create sub-component for selecting facets in single product view
- [x] create sub-component for price points in single product view
- [x] make it all look pretty-ish

**Comment by sarah-arrrgh** [comment]
Question:

- What does the data model look like for facets?

**Comment by ahdinosaur** [comment]
@sarah-arrrgh here's a draft attempt: https://github.com/root-systems/cobuy/issues/146#issuecomment-327697515. what do you think?

**Comment by sarah-arrrgh** [comment]
End of day/week report:

- scaffold product list item in storybook
- wired up single view product in storybook
- wireframed single view product on whiteboard (including facet and price point components)

**Comment by sarah-arrrgh** [comment]
![20170911_143556](https://user-images.githubusercontent.com/12442114/30256433-cdfe6eb4-96fe-11e7-9d4f-442ec161cb76.jpg)

**Comment by danalexilewis** [comment]
@sarah-arrrgh to me the view on the left looks like a mobile view and the right the view on desktop.

The view on the rleft reminds me of a card and I can imagine a list of cards (mobile) / grid of cards (desktop) to show items with a visually rich expierience. Is this what you were thinking?

**Comment by sarah-arrrgh** [comment]
@agentlewis the view on the left is the **product list view** - yes a grid of cards like you are imagining. and the view on the right is **single product view**, so has more info on the product including price points and facets.

**Comment by danalexilewis** [comment]
@sarah-arrrgh are you approaching this mobile first or skipping mobile?

**Comment by sarah-arrrgh** [comment]
End of day report:

- styled product list view 
- styled single product view
- changed currency display from `$` to `NZD` / `{currency}`

TODO:

- [x] check out the rest of Mikey's comments in the PR
- [x] screen shots of components in issue

**Comment by sarah-arrrgh** [comment]
Product list view:
![screen shot 2017-09-19 at 11 14 48 am](https://user-images.githubusercontent.com/12442114/30568908-e85eda40-9d2b-11e7-82cf-00d36fbbdd11.png)

Single product view:
![screen shot 2017-09-19 at 11 15 11 am](https://user-images.githubusercontent.com/12442114/30568912-eb168012-9d2b-11e7-9421-3d5e7cb758fc.png)

**Comment by sarah-arrrgh** [comment]
@agentlewis hmmm haven't been doing this mobile first

**Comment by danalexilewis** [comment]
This is going to come up very quickly as people will say "does it work on mobile". My personal opinion is that it is easier and more effective to develop from mobile to desktop rather then the other way round. Nvm to much - functionality is more important.

I'd suggest you break out a ticket to mobilise what you have done so far. We don't need it for the 27th but will before a beta test.

**Comment by danalexilewis** [comment]
@sarah-arrrgh see above
