### ISSUE TITLE
setup design style guide

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#68]
when i want to work on a Cobuy component, it should be clear how to follow the Cobuy style.

this guide will operate as a source of truth for design decisions that affect the whole app, and should be updated after the initial creation to keep everything up to date as design decisions change.

maybe pull relevant content from material ui style guide:

- colors
- typography
- material ui theme

use `rem`!

maybe use typography js?

MAYBE LATER

- layout guide (overview of grid system)

**Comment by gregorykan** [comment]
closes https://github.com/root-systems/cobuy/pull/78

**Comment by ahdinosaur** [comment]
@gregorykan potential other considerations:

- normalizing default styles like [GitHub's base css](https://github.com/primer/primer-css/tree/master/modules/primer-base/lib)
  - we already use `normalize.css`, but the other code they have is great for removing the default margins and paddings from elements, i often find myself annoyed by these things.
- compiling a list of existing style guides and css toolkits, in case we want prior art when implementing styles
  - https://material.io/
  - https://github.com/cloudflare/cf-ui
  - https://github.com/primer/primer-css
  - http://tachyons.io/
  - http://milligram.io/
  - https://github.com/franciscop/picnic
  - others in https://github.com/root-systems/dogstack/issues/13
- decide on a grid / box system
  - use [flexbox](https://caniuse.com/#feat=flexbox) directly via fela rules
  - use [css grids](https://caniuse.com/#feat=css-grid) directly via fela rules
  - https://kilvin.js.org/
  - https://github.com/rofrischmann/react-layout-components
  - any number of other favorites, there are heaps

**Comment by gregorykan** [comment]
@ahdinosaur re grid system i think kilvin would be an obvious choice to start with, considering both react layout components + fela ~

**Comment by gregorykan** [comment]
hmmm but also this https://github.com/queckezz/veel

**Comment by ahdinosaur** [comment]
from https://github.com/root-systems/cobuy/pull/122#discussion_r132874662, @sarah-arrrgh shared some sweet links about typographic scales:

- http://spencermortensen.com/articles/typographic-scale/
- https://blog.madewithenvy.com/responsive-typographic-scales-in-css-b9f60431d1c4

so i'm keen to revise our typographic scale to use the "pentatonic scale" (doubles every fifth step) as described, plus using `em` instead of `rem` when using this scale as recommended in the second article.

```
2^(5/5)      ->  2
2^(4/5)      ->  1.7411
2^(3/5)      ->  1.51572
2^(2/5)      ->  1.31951
2^(1/5)      ->  1.14869
2^(-1/5)     ->  0.87055
2^(-2/5)     ->  0.75785
2^(-3/5)     ->  0.65975
2^(-4/5)     ->  0.57435
2^(-5/5)     ->  0.5
```

so if we follow the second article's advise about using a single up/down scale and nesting `em`s, we might use:

```js
const fontSizes = {
  '-5': 0.50000,
  '-4': 0.57435, 
  '-3': 0.65975,
  '-2': 0.75785,
  '-1': 0.87055,
  0: 1.00000,
  1: 1.14869,
  2: 1.31951,
  3: 1.51572,
  4: 1.74110,
  5: 2.00000,
  // continue with formula:
  //   multiplier ^ (step / interval)
  //   2 ^ (step / 4)
]
```

or more like we did it before:

```js
const fontSizes = {
  0.50000, // [0]
  0.57435, // [1]
  0.65975, // [2]
  0.75785, // [3]
  0.87055, // [4]
  1.00000, // [5]
  1.14869, // [6]
  1.31951, // [7]
  1.51572, // [8]
  1.74110, // [9]
  2.00000, // [10]
  // continue with formula:
  //   multiplier ^ (step / interval)
  //   2 ^ (step / 4)
]
```

we might also want to apply this to the spacing scales, as this feels like a more flexible way to achieve the same clarity and consistency as with the exponential scale (basically doubles every step, not every 5 steps).

**Comment by sarah-arrrgh** [comment]
There's overlap between this ticket/issue and this wiki
https://github.com/root-systems/cobuy/wiki/Notable-notes

Maybe good to have one source of truth?

**Comment by ahdinosaur** [comment]
👍 to bring any notable notes from this issue to the wiki.

this issue is open as a task to _change_ our style theme to be based on the pentatonic scales described above.

**Comment by danalexilewis** [comment]
Can someone confirm we are building all components mobile first?
