### ISSUE TITLE
style member invites component

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#70]

**Comment by gregorykan** [comment]
![Screen Shot 2017-07-11 at 1.35.53 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/554158c23ae54b6500e6c8b0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f26b7191a379f1112e4f5a5c5ecc3c4a4356bcbbd671f3e57862804e0ee5833b5772c03c16aeb8d617b902be208b4784e4e98e1ad2f42f67b6d5db1063474f4dcbed5727a29f41c95cff42e64e53ad143f64e1722431.png)

**Comment by ahdinosaur** [comment]
![ssb-profile](https://user-images.githubusercontent.com/719605/28047797-c5824e8e-6640-11e7-9daf-b42b5add708e.png)
![ssb-profile1](https://user-images.githubusercontent.com/719605/28047794-c29b779a-6640-11e7-82a7-1b032631e5ec.png)

**Comment by gregorykan** [comment]
![Screen Shot 2017-07-11 at 5.36.42 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/554158c23ae54b6500e6c8b0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f26b7191a37df1112d4f5b5d5ecc3c4a4356bcbbd671f3e57862804e0ee5833b5772c03c16aeb8d617b902be208b4784e4e98e1ad2f42f67b6d5db1063474f4dcbed5727a29f41c95cff42e64854a0113366e3762431.png)

**Comment by gregorykan** [comment]
![Screen Shot 2017-07-11 at 5.38.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/554158c23ae54b6500e6c8b0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f26b7191a37df111234f5c575ecc3c4a4356bcbbd671f3e57862804e0ee5833b5772c03c16aeb8d617b902be208b4784e4e98e1ad2f42f67b6d5db1063474f4dcbed5727a29f41c95cff42e64854a1153663e07f2431.png)
