### ISSUE TITLE
scope dashboard and navigation

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#76]

**Comment by ahdinosaur** [comment]
first draft:

- Navigation
  - use [font awesome hamburger icon in top left](http://fontawesome.io/icon/bars/) (NavigationToggle) in [material ui app bar](http://www.material-ui.com/#/components/app-bar) (NavigationBar) to toggle [material ui drawer](http://www.material-ui.com/#/components/drawer) (NavigationDrawer)
- NavigationMenu
  - shows "LogOut", "My Profile", "My Groups", "My Tasks" buttons
  - split menu into sections with [material ui subheader](http://www.material-ui.com/#/components/subheader) or [material ui divider](http://www.material-ui.com/#/components/divider)
- Dashboard
  - links to "My Profile"
  - lists "My Groups",
    - per group, lists "My Tasks"
  - split into sections with [material ui subheader](http://www.material-ui.com/#/components/subheader)

**Comment by danalexilewis** [comment]
I have a licence for fa 5

**Comment by danalexilewis** [comment]
There is also a menu in the material ui pack, https://material.io/icons/ search for menu

**Comment by ahdinosaur** [comment]
> I have a licence for fa 5

:-1: on using any proprietary content in Cobuy

another example is not using the latest [EmojiOne](https://github.com/emojione/emojione) (a project that became successful by being the best open source emojis), because the new version is now proprietary.

**Comment by danalexilewis** [comment]
confused: http://fontawesome.io/license/

i have a pro licence as a supporter - i think that just means i have access to svgs or something. I guess the point is not to use the licence though.

**Comment by ahdinosaur** [comment]
yeah, i think the license for Font Awesome 5 is different than the license for Font Awesome 4 described on that page.
