### ISSUE TITLE
component: Navigation

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/cobuy#95]
should be something like: https://negomi.github.io/react-burger-menu/, but with material ui.

- NavigationToggle
  - [font awesome hamburger icon](http://fontawesome.io/icon/bars/) (we already have fa installed)
- NagivationBar
  - [material ui app bar](http://www.material-ui.com/#/components/app-bar) (NavigationBar)
- NavigationDrawer
  - [material ui drawer](http://www.material-ui.com/#/components/drawer)
- NavigationMenu
  - shows "LogOut", "Dashboard" buttons (for now)
  - split menu into sections with [material ui subheader](http://www.material-ui.com/#/components/subheader) or [material ui divider](http://www.material-ui.com/#/components/divider)

**Comment by ahdinosaur** [comment]
would be sweet if component took props similar to existing [nav.js](https://github.com/root-systems/cobuy/blob/fb3fcd3b1682ed8a639384acfd42e3c2566a1487/app/components/nav.js), where [routes are specified as an array of objects](https://github.com/root-systems/cobuy/blob/fb3fcd3b1682ed8a639384acfd42e3c2566a1487/routes.js) and [massaged in a getter](https://github.com/root-systems/cobuy/blob/fb3fcd3b1682ed8a639384acfd42e3c2566a1487/app/getters.js). i'm also thinking this should really be it's own topic `navigation`.

**Comment by gregorykan** [comment]
![app-bar-side-nav.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/554158c23ae54b6500e6c8b0/125516c66e82c728ace21e0d46e9848a6e8082bbc2fab647a110fe953f046b313916ac217586f76ae5002e590d0946aa47595846fcad812da5b23c70825d59b8d53b4d68d47f40f2ecdd42e64bef62994597b5bd804dc4e1342ce58c8f493a1c061e9bb2.gif)

**Comment by gregorykan** [comment]
@ahdinosaur i haven't done anything re: props and array of routes, just FYI ! this is srsly dumb-rock stuff - wouldn't be hard tho !
